name: builder_docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Software
      run: sudo apt-get install -yq sudo time git-core build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget python3.6 python3.10 libelf1 libelf-dev docker

    - name: Build Dockerimage
      run: docker build -t openwrt . 

    - name: Build OpenWRT
      run: docker run  --rm -ti -v $PWD/bin:/home/openwrt/bin -v $PWD/build_dir:/home/openwrt/build_dir -v $PWD/dl:/home/openwrt/dl exec make

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binary
        path: bin
